In [3]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel(r"C:\Users\HP\Downloads\Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [3]:
df=df.drop_duplicates()
df=df.drop(columns="Not_Useful_Column")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [4]:
df["Last_Name"] = df["Last_Name"].str.strip("..._/")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [5]:
df["Phone_Number"] = df["Phone_Number"].str.replace("-","")
df["Phone_Number"] = df["Phone_Number"].str.replace("|","")
df["Phone_Number"] = df["Phone_Number"].str.replace("/","")
df["Phone_Number"] = df["Phone_Number"].str.replace("N/a","")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na,N/a,N/a,Yes
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N

In [6]:
df["Phone_Number"]= df["Phone_Number"].apply(lambda x: str(x))
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,1235455421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes
2,1003,Walter,White,nan,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,1235432345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,3047622467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan,1209 South Street,No,No
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,1235455421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,nan,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,nan,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,1235432345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,3047622467,214 HR Avenue,N,No
15,1016,Ron,Weasley,1235455421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,nan,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na,N/a,N/a,Yes
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N

In [7]:
df["Phone_Number"]=df["Phone_Number"].apply(lambda x: x[0:3] + "-" + x[3:6] + "-" + x[6:10])
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,nan--,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan--,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na--,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [8]:
df["Phone_Number"] = df["Phone_Number"].str.replace("nan--","")
df["Phone_Number"] = df["Phone_Number"].str.replace("--","")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [9]:
#df[["Street_Address", "State", "Zip_Code"]] = df["Address"].str.split(',',2, expand=True)
#the above didnt work for me
#s=df["Address"].str.split(pat=" ",n=0, expand = True)
s=df["Address"].str.split(pat=",",n=1, expand = True)
s

                       0                     1
0         123 Shire Lane                 Shire
1    93 West Main Street                  None
2     298 Drugs Driveway                  None
3       980 Paper Avenue   Pennsylvania, 18503
4       123 Dragons Road                  None
5       768 City Parkway                  None
6      1209 South Street                  None
7          98 Clue Drive                  None
8       123 Middle Earth                  None
9       25th Main Street              New York
10        612 Shire Lane                 Shire
11  2394 Hogwarts Avenue                  None
12      2039 Main Street                  None
13      343 City Parkway                  None
14         214 HR Avenue                  None
15  2395 Hogwarts Avenue                  None
16      121 Paper Avenue          Pennsylvania
17       3498 Super Lane                  None
18                   N/a                  None
19     910 Tatooine Road              Tatooine

In [10]:
df["Street_Address"]=s[0]
df["State"]=s[1]
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,None
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,"Pennsylvania, 18503"
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,None
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,768 City Parkway,None
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,None
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN,123 Middle Earth,None
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,25th Main Street,New York
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,2039 Main Street,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,None
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,214 HR Avenue,None
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None
18,1019,Creed,Braton,Na,N/a,N/a,Yes,N/a,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine

In [11]:
s=df["Street_Address"].str.split(pat=" ",n=1, expand = True)
s

       0                 1
0    123        Shire Lane
1     93  West Main Street
2    298    Drugs Driveway
3    980      Paper Avenue
4    123      Dragons Road
5    768      City Parkway
6   1209      South Street
7     98        Clue Drive
8    123      Middle Earth
9   25th       Main Street
10   612        Shire Lane
11  2394   Hogwarts Avenue
12  2039       Main Street
13   343      City Parkway
14   214         HR Avenue
15  2395   Hogwarts Avenue
16   121      Paper Avenue
17  3498        Super Lane
18   N/a              None
19   910     Tatooine Road

In [12]:
df["Zip_code"]=s[0]
df["Street_Address"]=s[1]

In [13]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,Shire Lane,Shire,123
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,West Main Street,None,93
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,Drugs Driveway,None,298
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,Paper Avenue,"Pennsylvania, 18503",980
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,Dragons Road,None,123
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,City Parkway,None,768
6,1007,Jeff,Winger,,1209 South Street,No,No,South Street,None,1209
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,Clue Drive,None,98
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN,Middle Earth,None,123
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,Main Street,New York,25th
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,Shire Lane,Shire,612
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,Hogwarts Avenue,None,2394
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,Main Street,None,2039
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,City Parkway,None,343
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,HR Avenue,None,214
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,Hogwarts Avenue,None,2395
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,Paper Avenue,Pennsylvania,121
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,Super Lane,None,3498
18,1019,Creed,Braton,Na,N/a,N/a,Yes,None,None,N/a
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,Tatooine Road,Tatooine,910

In [14]:
df["Paying Customer"]=df["Paying Customer"].str.replace("Yes","Y")
df["Paying Customer"]=df["Paying Customer"].str.replace("No","N")
df["Paying Customer"]=df["Paying Customer"].str.replace("N/a","")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,No,Shire Lane,Shire,123
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Yes,West Main Street,None,93
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,Drugs Driveway,None,298
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,Paper Avenue,"Pennsylvania, 18503",980
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,Dragons Road,None,123
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Yes,City Parkway,None,768
6,1007,Jeff,Winger,,1209 South Street,N,No,South Street,None,1209
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,Clue Drive,None,98
8,1009,Gandalf,NaN,Na,123 Middle Earth,Y,NaN,Middle Earth,None,123
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,No,Main Street,New York,25th
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,No,Shire Lane,Shire,612
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,Hogwarts Avenue,None,2394
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,Main Street,None,2039
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,No,City Parkway,None,343
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No,HR Avenue,None,214
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,Hogwarts Avenue,None,2395
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,No,Paper Avenue,Pennsylvania,121
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,Super Lane,None,3498
18,1019,Creed,Braton,Na,N/a,,Yes,None,None,N/a
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,Tatooine Road,Tatooine,910

In [15]:
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace("No","N")
df["Do_Not_Contact"]=df["Do_Not_Contact"].str.replace("Yes","Y")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,Shire Lane,Shire,123
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,N,Y,West Main Street,None,93
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,Drugs Driveway,None,298
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Y,Y,Paper Avenue,"Pennsylvania, 18503",980
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,Dragons Road,None,123
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Y,Y,City Parkway,None,768
6,1007,Jeff,Winger,,1209 South Street,N,N,South Street,None,1209
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,Clue Drive,None,98
8,1009,Gandalf,NaN,Na,123 Middle Earth,Y,NaN,Middle Earth,None,123
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,Main Street,New York,25th
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Y,N,Shire Lane,Shire,612
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,Hogwarts Avenue,None,2394
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,Main Street,None,2039
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,City Parkway,None,343
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,HR Avenue,None,214
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,Hogwarts Avenue,None,2395
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,Paper Avenue,Pennsylvania,121
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,Super Lane,None,3498
18,1019,Creed,Braton,Na,N/a,,Y,None,None,N/a
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,Tatooine Road,Tatooine,910

In [25]:
df= df.replace("N/a","")
df= df.replace("Na","")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,Shire Lane,Shire,123
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,Dragons Road,,123
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,Clue Drive,,98
8,1009,Gandalf,,,123 Middle Earth,Y,,Middle Earth,,123
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,Main Street,New York,25th
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,Main Street,,2039
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,City Parkway,,343
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,HR Avenue,,214
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,Hogwarts Avenue,,2395
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,Paper Avenue,Pennsylvania,121
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,Tatooine Road,Tatooine,910

In [26]:
df=df.fillna("")

In [27]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,Shire Lane,Shire,123
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,Dragons Road,,123
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,Clue Drive,,98
8,1009,Gandalf,,,123 Middle Earth,Y,,Middle Earth,,123
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,Main Street,New York,25th
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,Main Street,,2039
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,City Parkway,,343
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,HR Avenue,,214
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,Hogwarts Avenue,,2395
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,Paper Avenue,Pennsylvania,121
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,Tatooine Road,Tatooine,910

In [28]:
for x in df.index:
    if df.loc[x,"Do_Not_Contact"] =="Y":
        df.drop(x,inplace = True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,Shire Lane,Shire,123
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,Dragons Road,,123
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,Clue Drive,,98
8,1009,Gandalf,,,123 Middle Earth,Y,,Middle Earth,,123
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,Main Street,New York,25th
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,Main Street,,2039
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,City Parkway,,343
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,HR Avenue,,214
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,Hogwarts Avenue,,2395
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,Paper Avenue,Pennsylvania,121
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,Tatooine Road,Tatooine,910

In [29]:
#df=df.dropna(subset="Phone_Number",inplace = True)
#another way to drop null values
for x in df.index:
    if df.loc[x,"Phone_Number"] =="":
        df.drop(x,inplace = True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,Shire Lane,Shire,123
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,Dragons Road,,123
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,Clue Drive,,98
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,Main Street,New York,25th
12,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,Main Street,,2039
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,City Parkway,,343
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,HR Avenue,,214
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,Hogwarts Avenue,,2395
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,Paper Avenue,Pennsylvania,121
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,Tatooine Road,Tatooine,910

In [30]:
df.reset_index(drop=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street_Address,State,Zip_code
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Y,N,Shire Lane,Shire,123
1,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,N,Dragons Road,,123
2,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,N,Clue Drive,,98
3,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Y,N,Main Street,New York,25th
4,1013,Don,Draper,123-543-2345,2039 Main Street,Y,N,Main Street,,2039
5,1014,Leslie,Knope,876-678-3469,343 City Parkway,Y,N,City Parkway,,343
6,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,N,HR Avenue,,214
7,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,N,N,Hogwarts Avenue,,2395
8,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Y,N,Paper Avenue,Pennsylvania,121
9,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Y,N,Tatooine Road,Tatooine,910